package com.explr.explravenue.rapyd.collect.checkout.response

data class Data(
    var id: String = "",
    var status: String = "",
    var language: String = "",
    var merchant_color: Any = Any(),
    var merchant_logo: Any = Any(),
    var merchant_website: String = "",
    var merchant_customer_support: MerchantCustomerSupport = MerchantCustomerSupport(),
    var merchant_alias: String = "",
    var merchant_terms: Any = Any(),
    var merchant_privacy_policy: Any = Any(),
    var page_expiration: Int = 0,
    var redirect_url: String = "",
    var merchant_main_button: String = "",
    var cancel_checkout_url: String = "",
    var complete_checkout_url: String = "",
    var country: String = "",
    var currency: String = "",
    var amount: Double = 0.0,
    var payment: Payment = Payment(),
    var payment_method_type: Any = Any(),
    var payment_method_type_categories: Any = Any(),
    var payment_method_types_include: List<String> = listOf(),
    var payment_method_types_exclude: List<Any> = listOf(),
    var customer: String = "",
    var custom_elements: CustomElements = CustomElements(),
    var timestamp: Int = 0,
    var payment_expiration: Any = Any(),
    var cart_items: List<Any> = listOf(),
    var escrow: Any = Any(),
    var escrow_release_days: Any = Any()
)